site_name: litestar-rs
site_description: Distributed task queue on Redis Streams with first-class Litestar integration
site_url: https://github.com/smirnoffmg/litestar-rs

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true

nav:
  - Home: index.md
  - API: api.md
