"""Distributed task queue on Redis Streams with first-class Litestar integration.

Delivery is at-least-once: handlers must be idempotent.
"""

from importlib.metadata import version as _version

from litestar_rs.core import (
    BrokerHandler,
    Codec,
    CollectingEnqueuer,
    ConfigurationError,
    CronJob,
    DeferredEnqueuer,
    EagerEnqueuer,
    Enqueuer,
    Envelope,
    FilePayloadStore,
    JsonCodec,
    LitestarRsError,
    MalformedEnvelope,
    PayloadMissing,
    PayloadStore,
    PayloadTooLarge,
    Pending,
    Record,
    RedisResultStore,
    RedisScheduler,
    RedisStreamsTransport,
    ResultStore,
    RetryPolicy,
    Scheduler,
    StreamTransport,
    TaskHandler,
    TaskResult,
    UnknownTask,
    WorkerConfig,
    WorkerStats,
    current_enqueuer,
    dlq_key,
    from_fields,
    run,
    run_with_signals,
    to_fields,
    worker_running,
)

__version__ = _version("litestar-rs")
"""Read from the installed metadata: pyproject is the only place it is written."""

__all__ = [
    "BrokerHandler",
    "Codec",
    "CollectingEnqueuer",
    "ConfigurationError",
    "CronJob",
    "DeferredEnqueuer",
    "EagerEnqueuer",
    "Enqueuer",
    "Envelope",
    "FilePayloadStore",
    "JsonCodec",
    "LitestarRsError",
    "MalformedEnvelope",
    "PayloadMissing",
    "PayloadStore",
    "PayloadTooLarge",
    "Pending",
    "Record",
    "RedisResultStore",
    "RedisScheduler",
    "RedisStreamsTransport",
    "ResultStore",
    "RetryPolicy",
    "Scheduler",
    "StreamTransport",
    "TaskHandler",
    "TaskResult",
    "UnknownTask",
    "WorkerConfig",
    "WorkerStats",
    "__version__",
    "current_enqueuer",
    "dlq_key",
    "from_fields",
    "run",
    "run_with_signals",
    "to_fields",
    "worker_running",
]
